---
- name: CERT-MANAGER - Add cert-manager helm repo
  kubernetes.core.helm_repository:
    name: jetstack
    repo_url: https://charts.jetstack.io
    kubeconfig_path: "{{ kube_config_path }}"

- name: CERT-MANAGER - Deploy cert-manager
  kubernetes.core.helm:
    kubeconfig_path: "{{ kube_config_path }}"
    name: cert-manager
    chart_ref: jetstack/cert-manager
    chart_version: 1.15.0
    update_repo_cache: true
    namespace: cert-manager
    create_namespace: true
    release_state: present
    set_values:
      - value: crds.enabled=true
        value_tupe: string
